SOCIAL_MEDIA_LIST = ["Instagram", "Facebook", "Twitter", "LinkedIn"]
MOODS = ["Neutral", "Informative", "Funny", "Inspirational", "Promotional", "Emotional"]

DEFAULT_EXAMPLES = [
    "A Wanderer on a Sea of Fog",
    "M'illumino d'immenso",
    "To travel is to live",
    "Cogito, ergo sum",
    "La vita è un viaggio, non una destinazione",
    "Somewhere only we know",
    "All we have is now",
    "La felicità è reale solo se condivisa",
    "Live by the sun, love by the moon",
    "Stay hungry, stay foolish",
    "Chi ha un perché abbastanza forte può superare qualsiasi come",
    "It always seems impossible until it's done",
    "Be the change you wish to see in the world",
    "La semplicità è l’ultima sofisticazione",
    "Il segreto del cambiamento è concentrare tutta la tua energia non nel combattere il vecchio, ma nel costruire il nuovo",
    "Not all those who wander are lost",
    "Dreams don’t work unless you do",
    "Il mondo è un libro, e quelli che non viaggiano ne leggono solo una pagina",
    "Create your own sunshine",
    "Andrà tutto bene",
    "We are made of star-stuff",
    "L’essenziale è invisibile agli occhi",
    "Life begins at the end of your comfort zone",
    "Ogni giorno è una nuova occasione per splendere",
    "Don’t count the days, make the days count",
]
